modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hotkettles"
version = "${version}"
displayName = "Hot Kettles"
authors = "Slainlight"
description = '''
Adds some fun drinks into Minecraft
'''
logoFile = "assets/hotkettles/icon.png"

[[mixins]]
config = "hotkettles-common.mixins.json"

[[dependencies.hotkettles]]
modId="minecraft"
type="required"
versionRange="[1.20.4]"

[[dependencies.hotkettles]]
modId="neoforge"
type="required"
versionRange="[20.4,)"

[[dependencies.hotkettles]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.1,)"
ordering = "AFTER"
side = "BOTH"